/** @format */

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "./Providers";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${inter.className}  w-full max-h-screen items-start  `}
        >
          <Navbar />
          <div className="max-w-5xl pt-4  mx-auto px-2  ">{children}</div>
        </body>
      </Providers>
    </html>
  );
}
